# Generated by Django 3.0.3 on 2020-06-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='basicapp.Client'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='basicapp.Consultant'),
        ),
        migrations.AlterField(
            model_name='operationstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operations', to='basicapp.Status'),
        ),
    ]
